version: '3'

services:
  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecurepass
      - POSTGRES_DB=hbhack-server_development
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  hbhack:
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=hbhack-server_development
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecurepass
    image: hbhack
    command: bash
    volumes:
      - ".:/usr/src/hbhack:cached"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
