version: '3'

services:
  hbhack:
    stdin_open: true
    tty: true
    volumes:
      - "hbhack-sync:/usr/src/hbhack:nocopy"
    ports:
      - "3000:3000"

volumes:
  hbhack-sync:
    external: true
