apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hbhack
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hbhack-ip
  labels:
    app: hbhack
spec:
  backend:
    serviceName: hbhack-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hbhack-backend
  labels:
    app: hbhack
spec:
  type: NodePort
  selector:
    app: hbhack
    tier: backend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
