apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hbhack
  labels:
    app: hbhack
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  selector:
    matchLabels:
      app: hbhack
      tier: backend
  template:
    metadata:
      labels:
        app: hbhack
        tier: backend
    spec:
      containers:
        - image: asia.gcr.io/michael-test-1425/hbhack:0.0.3
          name: hbhack
          env:
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: DATABASE_NAME
              value: "hbhack-server_production"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_URL
              value: "postgres"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: "db-user"
                  key: "username"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "db-user-pass"
                  key: "password"
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
          command:
            - rails
            - s
          volumeMounts:
            - name: puma
              mountPath: /usr/src/hbhack/config/puma.rb
              subPath: puma.rb
              readOnly: true
            - mountPath: /tmp
              name: sock
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              name: hbhack
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - mountPath: /tmp
              name: sock
      volumes:
        - name: sock
          emptyDir: {}
        - name: nginx
          configMap:
            name: nginx
        - name: puma
          configMap:
            name: puma
