default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hbhack-server_development

test:
  <<: *default
  database: hbhack-server_test

production:
  <<: *default
  database: hbhack-server_production
  url: <%= ENV['DATABASE_URL'] %>
